version: '3.7'

services:
  # Kafka with Zookeeper
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9092,OUTSIDE://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    depends_on:
      - zookeeper
  # kafka-init:
  #   image: wurstmeister/kafka
  #   depends_on:
  #     - kafka
  #   entrypoint: ["/bin/sh", "-c", "kafka-topics.sh --create --topic test --bootstrap-server localhost:9092 --partitions 3 --replication-factor 1"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=Sseuser
      - ELASTIC_PASSWORD=Sse2024
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_USERNAME=Sseuser
      - ELASTICSEARCH_PASSWORD=Sse2024
      - ELASTICSEARCH_HOSTS="http://elasticsearch:9200"

  # MySQL updated to version 8.0.31
  # mysql:
  #   image: mysql:8.0.31
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
  #     MYSQL_DATABASE: mydb
  #     MYSQL_USER: SSEuser
  #     MYSQL_PASSWORD: Sysusse2024
  #   ports:
  #     - "3307:3306"
  #   command: --default-authentication-plugin=mysql_native_password
  #   volumes:
  #   - ./mysql:/var/lib/mysql

  # # Flink jobmanager and taskmanager
  # jobmanager:
  #   image: flink:1.14.4
  #   ports:
  #     - "8081:8081"
  #   command: jobmanager
  #   environment:
  #     - JOB_MANAGER_RPC_ADDRESS=jobmanager
  #     - FLINK_PROPERTIES=execution.executor:standalone
  #   depends_on:
  #     - kafka
  #   # volumes:
  #   #   - ./lib:/opt/flink/lib

  # taskmanager:
  #   image: flink:1.14.4
  #   depends_on:
  #     - jobmanager
  #   command: taskmanager
  #   environment:
  #     - |
  #       FLINK_PROPERTIES=
  #       jobmanager.rpc.address: jobmanager
  #       taskmanager.numberOfTaskSlots: 2
  #   # volumes:
  #   #   - ./lib:/opt/flink/lib

  # doris-fe:
  #   image: apache/doris:2.0.3-fe-x86_64
  #   hostname: "doris-fe"
  #   environment:
  #     - FE_SERVERS=fe1:127.0.0.1:9010
  #     - FE_ID=1
  #     # - PRIORITY_NETWORKS=127.0.0.1
  #     # - DORIS_FE_ROLE=master
  #   ports:
  #     - 8030:8030
  #     - 9030:9030
  #   # volumes:
  #   #  - /data/fe/doris-meta/:/opt/apache-doris/fe/doris-meta/
  #   #  - /data/fe/log/:/opt/apache-doris/fe/log/
  #   network_mode: host

  # doris-be:
  #   image: apache/doris:2.0.3-be-x86_64
  #   hostname: "doris-be"
  #   depends_on:
  #     - doris-fe
  #   environment:
  #     - FE_SERVERS=fe1:127.0.0.1:9010
  #     - BE_ADDR=127.0.0.1:9050
  #     # - PRIORITY_NETWORKS=127.0.0.1
  #     # - BE_PORT=9060       # Doris BE port
  #     # - HTTP_PORT=8040     # Doris BE HTTP port
  #     # - BRPC_PORT=8060     # Doris BE BRPC port
  #   ports:
  #     - "8040:8040"       # Expose HTTP port
  #   #   # - "9050:9050"       # Expose BE_ADDR port
  #   #   # - "9060:9060"       # Expose Doris BE port
  #   #   # - "8060:8060"       # Expose BRPC port
  #   volumes:
  #     - ./limits.conf:/etc/security/limits.conf
  #     - ./sysctl.conf:/etc/sysctl.conf
  #     # - /data/be/storage/:/opt/apache-doris/be/storage/
  #     # - /data/be/script/:/docker-entrypoint-initdb.d/
  #   network_mode: host

  # fe:
  #   image: apache/doris:2.0.0_alpha-fe-x86_64
  #   hostname: fe
  #   environment:
  #    - FE_SERVERS=fe1:127.0.0.1:9010
  #    - FE_ID=1
  #   # ports:
  #   #   - 8030:8030
  #   #   - 9030:9030
  #   # volumes:
  #   #  - /data/fe/doris-meta/:/opt/apache-doris/fe/doris-meta/
  #   #  - /data/fe/log/:/opt/apache-doris/fe/log/
  #   network_mode: host
    
  # be:
  #   image: apache/doris:2.0.0_alpha-be-x86_64
  #   hostname: be
  #   environment:
  #    - FE_SERVERS=fe1:127.0.0.1:9010
  #    - BE_ADDR=127.0.0.1:9050
  #   # volumes:
  #   #  - /data/be/storage/:/opt/apache-doris/be/storage/
  #   #  - /data/be/script/:/docker-entrypoint-initdb.d/
  #   # ports:
  #   #   - "8040:8040"       # Expose HTTP port
  #   depends_on:
  #     - fe
  #   network_mode: host
    

  # doris-network:
  #   ipam:
  #     config:
  #       - subnet: 127.0.0.0/24

  # fe:
  #   image: "apache/doris:2.0.0_alpha-fe-x86_64"
  #   hostname: doris-fe
  #   container_name: "doris-fe"
  #   ports:
  #     - 8030:8030
  #     - 9030:9030
  #   environment:
  #     - FE_SERVERS=fe1:172.30.80.2:9010
  #     - FE_ID=1
  #   volumes:
  #     - /data/doris/fe_data/doris-meta:/opt/apache-doris/fe/doris-meta
  #     - /data/doris/fe_data/log:/opt/apache-doris/fe/log
  #   networks:
  #     doris_net:
  #       ipv4_address: 172.30.80.2
  # be:
  #   image: "apache/doris:2.0.0_alpha-be-x86_64"
  #   hostname: doris-be
  #   container_name: "doris-be"
  #   ports:
  #     - 8040:8040
  #   environment:
  #     - MASTER_FE_IP=172.30.80.2
  #     - CURRENT_BE_IP=172.30.80.3
  #     - CURRENT_BE_PORT=9050
  #     - FE_SERVERS=fe1:172.30.80.2:9010
  #     - BE_ADDR=172.30.80.3:9050
  #     - PRIORITY_NETWORKS=172.30.80.0/24
  #   volumes:
  #     - /data/doris/be_data/storage:/opt/apache-doris/be/storage
  #     - /data/doris/be_data/log:/opt/apache-doris/be/log
  #     - /data/doris/be_data/script:/docker-entrypoint-initdb.d
  #    #- /data/doris/be/be.conf:/opt/apache-doris/be/conf/be.conf
  #   depends_on:
  #     - fe
  #   networks:
  #     doris_net:
  #       ipv4_address: 172.30.80.3

networks:
  default:
    driver: bridge
  doris_net:
    ipam:
      config:
        - subnet: "172.30.80.0/24"

